/**
 * Generates supabase/seed.sql from the canonical DEFAULT_* content so it can be
 * pasted into the Supabase SQL editor (useful when the seeding host can't reach
 * Supabase directly). Uses Postgres dollar-quoting to avoid escaping apostrophes.
 *
 *   npx tsx scripts/gen-seed-sql.ts
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  DEFAULT_CONTENT,
  DEFAULT_DEMOS,
  DEFAULT_SESSIONS,
  DEFAULT_GALLERY,
  DEFAULT_FAQS,
} from "../lib/content";

const Q = "$ym$"; // dollar-quote tag; safe — never appears in content
const q = (v: string | number | boolean | null) =>
  v === null ? "null" : typeof v === "string" ? `${Q}${v}${Q}` : String(v);

const lines: string[] = [
  "-- Generated by scripts/gen-seed-sql.ts — do not edit by hand.",
  "-- Run AFTER 0001_init.sql. Loads the prototype content.",
  "",
  "insert into public.site_content (id, data) values",
  `  (1, ${Q}${JSON.stringify(DEFAULT_CONTENT)}${Q}::jsonb)`,
  "on conflict (id) do update set data = excluded.data, updated_at = now();",
  "",
];

const block = (
  table: string,
  cols: string[],
  rows: Record<string, string | number | boolean | null>[]
) => {
  lines.push(`delete from public.${table};`);
  lines.push(`insert into public.${table} (${cols.join(", ")}) values`);
  const vals = rows.map(
    (r, i) =>
      `  (${cols.map((c) => (c === "sort_order" ? i : q(r[c]))).join(", ")})`
  );
  lines.push(vals.join(",\n") + ";");
  lines.push("");
};

block(
  "demos",
  ["tag", "title", "maker", "body", "color", "sort_order"],
  DEFAULT_DEMOS
);
block(
  "sessions",
  ["date_label", "day", "title", "location", "spots", "luma_url", "is_next", "sort_order"],
  DEFAULT_SESSIONS
);
block(
  "gallery_photos",
  ["image_path", "date_label", "tilt", "sort_order"],
  DEFAULT_GALLERY
);
block("faqs", ["question", "answer", "sort_order"], DEFAULT_FAQS);

writeFileSync(resolve(process.cwd(), "supabase/seed.sql"), lines.join("\n"));
console.log("Wrote supabase/seed.sql");
